import os
import sys
import threading

# Add the parent directory to sys.path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from integrations import LinkedInIntegration
from gmail_automation import get_gmail_automation

def main():
    # Send test email
    print("--- Gmail Test ---")
    gmail = get_gmail_automation()
    if not gmail:
        print('Gmail not configured in .env (missing CLIENT_ID or CLIENT_SECRET)')
    else:
        if not gmail.is_authenticated():
            print('Gmail not authenticated. Initiating OAuth flow...')
            # Authorize will open a browser
            gmail.authorize()
            
        if gmail.is_authenticated():
            print('Gmail is authenticated. Sending email...')
            sent = gmail.send_email('ashwinkbd3@gmail.com', 'Test Email from AI Agent Builder', 'Hello, this is a test email sent automatically.', html=False)
            print('Email sent:', sent)
        else:
            print('Failed to authenticate Gmail.')

    print("\n--- LinkedIn Test ---")
    # Post to LinkedIn
    linkedin_token = os.getenv("LINKEDIN_ACCESS_TOKEN")
    if not linkedin_token:
        # Fallback to OAuthManager (db)
        from oauth_manager import OAuthManager
        oauth_mgr = OAuthManager()
        token_data = oauth_mgr.get_token('linkedin')
        if token_data and isinstance(token_data, dict):
             linkedin_token = token_data.get('access_token')
        elif token_data and isinstance(token_data, str):
             linkedin_token = token_data
        
    if not linkedin_token:
        print("LinkedIn not authenticated. Missing LINKEDIN_ACCESS_TOKEN in .env and not found in OAuthManager.")
        print("You need to set LINKEDIN_ACCESS_TOKEN manually or run the web server to authenticate via OAuth.")
    else:
        print("LinkedIn token found. Posting update...")
        linkedin = LinkedInIntegration(access_token=linkedin_token)
        post_res = linkedin.share_post('This is a test post generated by the AI Agent Builder script.')
        print('LinkedIn post result:', post_res)

if __name__ == '__main__':
    main()
